# Generated by Django 4.2.7 on 2024-01-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='number_version',
            new_name='version',
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
